# Generated by Django 4.2.7 on 2023-11-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_reply"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
