# Generated by Django 4.2.7 on 2023-11-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_contact_delete_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(default=1, max_length=240),
        ),
    ]
